# Heralding configuration file

# Where to store logs
log_file: '/var/log/heralding.log'

# Logging level
log_level: 'INFO'

# Directory where files served by the honeypot will be stored
data_dir: '/tmp'

# Where to report attacks
reporters:
  file:
    enabled: true
    session_log_file: '/log_session.json'
    auth_log_file: '/log_auth.csv'
    # Добавляем путь к CSV файлу сессий
    session_csv_log_file: '/log_session.csv'

# Configuration for the supported protocols
protocols:
  ftp:
    enabled: true
    port: 21
    max_attempts: 3
    banner: "FTP server ready."
  
  ssh:
    enabled: true
    port: 2221
    banner: "SSH-2.0-OpenSSH_6.7p1 Debian-5+deb8u4"
    max_attempts: 3
  
  http:
    enabled: true
    port: 80
    banner: "Microsoft-IIS/8.0"
    max_attempts: 3
  
  https:
    enabled: true
    port: 443
    banner: "Microsoft-IIS/8.0"
    max_attempts: 3
    cert_file: '/heralding/cert.pem'
    key_file: '/heralding/key.pem'
  
  pop3:
    enabled: true
    port: 110
    max_attempts: 3
    banner: "+OK POP3 server ready"
  
  pop3s:
    enabled: true
    port: 995
    max_attempts: 3
    banner: "+OK POP3 server ready"
    cert_file: '/heralding/cert.pem'
    key_file: '/heralding/key.pem'
  
  smtp:
    enabled: true
    port: 25
    banner: "220 ESMTP Postfix"
    max_attempts: 3
  
  telnet:
    enabled: true
    port: 2323
    max_attempts: 3

  vnc:
    enabled: true
    port: 5900
    max_attempts: 3

general:
  # Addresses to listen on
  # 0.0.0.0 = All IPv4 addresses
  # :: = All IPv6 addresses
  host: 0.0.0.0
  
  # Enable proxy detection
  activity_tracking: true
  
  # Force authentication to fail
  auth_fail: true
  
  # Timeout in seconds for TCP connections
  timeout_seconds: 30
  
  # Timeout for active sessions
  timeout_active_sessions: 300
  
  # Minimum time to hold the session open
  # before hanging up after authentication
  # attempt regardless of the protocol
  # specifications
  # Set this to 0 to disable
  min_time_between_auth: 0.1
