filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/cowrie/cowrie.json
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true
  fields:
    honeypot: "cowrie"
    source_type: "cowrie-json"
  fields_under_root: true
  tags: ["cowrie"]

- type: log
  enabled: true
  paths:
    - /var/log/heralding/log_session.json
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true
  fields:
    honeypot: "heralding"
    log_type: "session_json"
    source_type: "heralding-json" 
  fields_under_root: true
  tags: ["heralding"]

- type: log
  enabled: true
  paths:
    - /var/log/heralding/log_auth.csv
  fields:
    honeypot: "heralding"
    log_type: "auth_csv"
    source_type: "heralding-csv"
  fields_under_root: true
  tags: ["heralding"]

- type: log
  enabled: true
  paths:
    - /var/log/heralding/log_session.csv
  fields:
    honeypot: "heralding"
    log_type: "session_csv"
    source_type: "heralding-csv"
  fields_under_root: true
  tags: ["heralding"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
  index: "%{[honeypot]}"

http.enabled: true
http.host: 0.0.0.0
